
# Based on the Goreleaser configuration provided at:
# https://github.com/hashicorp/terraform-provider-scaffolding
#
# Artifacts must be produced matching the layout described at:
# https://www.terraform.io/docs/registry/providers/publishing.html
version: 2
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
      # - GPG_PRIVATE_KEY=${{ secrets.GPG_PRIVATE_KEY }}
      # - PASSPHRASE=${{ secrets.PASSPHRASE }}
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    binary: '{{ .ProjectName }}_v{{ .Version }}'
# archives:
#   - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
# checksum:
#   name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
#   algorithm: sha256

archives:
  - format: zip
    name_template: >-
      terraform-provider-{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - none*

checksum:
  name_template: terraform-provider-cmccloudv2_{{ .Version }}_SHA256SUMS
  algorithm: sha256
signs:
  # - disable: true
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
release:
  draft: true
changelog:
  disable: true
